Update README example to the latest commit (#223)
Why:
The example commit is so old, it dates back to when this repo was called
codechecker_bazel, which actually results in an error:
```
ERROR: Error computing the main repository mapping:
  in module dependency chain <root> -> rules_codechecker@_:
  the MODULE.bazel file of rules_codechecker@_ declares a different name (bazel_codechecker)
```

What:
Use the latest commit in the `MODULE.bazel` example snippet in README.

Addresses:

---------

Co-authored-by: F.Tibor <tibi.furesz@gmail.com>